# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Projects\KLSH_Sender\design/help.ui'
#
# Created by: PyQt5 UI code generator 5.15.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Help(object):
    def setupUi(self, Help):
        Help.setObjectName("Help")
        Help.resize(686, 403)
        self.gridLayout_2 = QtWidgets.QGridLayout(Help)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(Help)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.textBrowser = QtWidgets.QTextBrowser(Help)
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout.addWidget(self.textBrowser, 1, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(Help)
        QtCore.QMetaObject.connectSlotsByName(Help)

    def retranslateUi(self, Help):
        _translate = QtCore.QCoreApplication.translate
        Help.setWindowTitle(_translate("Help", "Dialog"))
        self.label.setText(_translate("Help", "Справка"))
        self.textBrowser.setHtml(_translate("Help", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">Это приложение сделано для того, чтобы отправлять почту КЛШ, не используя при этом большое количество зондеров. <br />-Первым делом необходимо ввести логин и пароль от почты.<br />-Потом нужно выбрать XLSX файл со школьниками и указать номера колонок, начиная с единицы.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">-Указать HTML файл-шаблон письма, в котором нужно расставить места для подстановки имени и других значений<br />-Указать альтернативное письмо (если письмо в формате html не может отобразиться, то будет отображено альтернативное письмо</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">После того, как все действия были проделаны, необходимо удостовериться, что на вашем аккаунте разрешено использование сторонними приложениями данных для отправки. Инструкция здесь: https://palpalych.ru/blog/nastrojka-otpravki-pochty-gmail-cherez-smtp-problemy-s-gsuite-i-smtp-storonnih-prilozhenij<br />Теперь можно нажать кнопку отправить.<br /><br />Инструкция по созданию html файла приложена к программе.</span></p></body></html>"))
